import { ToastContainer,toast } from "react-toastify";

import "react-toastify/dist/ReactToastify.css";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from '@/components/navigation'
import FinanceContextProvider from "@/lib/store/financecontext";

import AuthContextProvider from "@/lib/store/auth-context";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthContextProvider>
          <FinanceContextProvider>
            <ToastContainer/>
            <Nav/>{children}
          </FinanceContextProvider>
        </AuthContextProvider>
       </body>
      
    </html>
  );
}
